name: Continuous-Deployment
on:
  workflow_run:
    workflows: ["Continuous-Integration"]
    types:
      - completed
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    strategy:
      matrix:
        node: ["16.x"]
    steps:
      - name: Checking out Shelf Health API coder
        uses: actions/checkout@v2
        
      # - name: minisauras
      #   uses: TeamTigers/minisauras@v2.0.0
      #   with:         
      #     directory: ./ # default is ./

      - name: Deploying to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
